---
abstract: 'RT Extension-LDAPImport-MultiEmail Extension'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-LDAPImport-MultiEmail
no_index:
  directory:
    - inc
    - t
requires:
  RT::Extension::LDAPImport: 0
  RT::Extension::MergeUsers: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.02
