---
abstract: 'RT-Extension-LDAPImport-MultiEmail Extension'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.08'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-LDAPImport-MultiEmail
no_index:
  directory:
    - inc
    - t
requires:
  RT::Extension::LDAPImport: 0
  RT::Extension::MergeUsers: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '0.03'
x_module_install_rtx_version: 0.34_04
x_requires_rt: 4.0.0
x_requires_rt_plugins:
  - RT::Extension::MergeUsers
